In [1]:
import math as m
import numpy as np
import pandas as pd
from itertools import islice

In [32]:
p1 = [0, 1]
p2 = [1, 2]
p3 = [2, 1]
p4 = [1, 0]


In [33]:
theta = m.atan2(p3[1]-p2[1], p3[0]-p2[0]) 
print(theta * 180/m.pi)

-45.0


In [34]:
theta2 = m.atan2(p1[1]-p2[1], p1[0]-p2[0])
print(theta2 * 180/m.pi)

-135.0


In [35]:
res = theta - theta2
print(res * 180/m.pi)

90.0


In [36]:
theta3 = m.atan2(p4[1]-p3[1], p4[0]-p3[0]) 
print(theta3 * 180/m.pi)

-135.0


In [37]:
theta4 = m.atan2(p2[1]-p3[1], p2[0]-p3[0])
print(theta4 * 180/m.pi)

135.0


In [38]:
res2 = theta3 - theta4
print(res2 *180/m.pi )

-270.0


In [52]:
if (abs(res2) > m.pi ):
    res2 = res2 < 0 if 2 * m.pi + res2 else 2 * m.pi - res2
print(res2 *180/m.pi)

90.0


In [39]:
smooth = res + res2
print(smooth*180/m.pi)

-180.0


In [40]:
theta5 = m.atan2(p3[1]-p4[1], p3[0]-p4[0]) #quando trasli prendi il modulo (altrimenti casino con coordinate negative)
print(theta5 * 180/m.pi)

45.0


In [41]:
theta6 = m.atan2(p1[1]-p4[1], p1[0]-p4[0])
print(theta6*180/m.pi)

135.0


In [42]:
res3 = theta5 - theta6
print(res3 *180/m.pi )

-90.0


In [43]:
smooth2 = smooth + res3
print(smooth2 *180/m.pi)

-270.0


In [62]:
# Algorithm

# compute the angle given points p1, p2, p3 being p2 the point where the 'turning' happens
angle = m.atan2(p3[1]-p2[1], p3[0]-p2[0]) - m.atan2(p1[1]-p2[1], p1[0]-p2[0])
print("Before conversion: ", angle * 180/m.pi)

# if the angle is greater than 180° convert it to a value x such that -pi<x<+pi
if (abs(angle) > m.pi ):
    angle = 2 * m.pi + angle if angle < 0 else -2 * m.pi + angle
print("After conversion: ", angle * 180/m.pi)

Before conversion:  90.0
After conversion:  90.0


In [2]:
ground_truth_poses_df = pd.read_csv('/home/emanuele/Desktop/ground_truth_poses.csv')
ground_truth_positions = ground_truth_poses_df[['x', 'y']].values
deltas = (ground_truth_positions[1:-1] - ground_truth_positions[0:-2])

In [3]:
ground_truth_poses_df

t  x  y     theta       v_x       v_y   v_theta
0  7.271  0  1  1.963334 -0.000200  0.000722 -0.000692
1  7.321  1  2  1.963333 -0.000245  0.000760 -0.000698
2  7.371  2  1  1.932275  0.051480 -0.132363 -0.925212
3  7.421  3  2  1.901164  0.015751 -0.020321  0.121696
4    NaN  0  0       NaN       NaN       NaN       NaN

In [4]:
ground_truth_positions

array([[0, 1],
       [1, 2],
       [2, 1],
       [3, 2],
       [0, 0]])

In [5]:
ground_truth_positions[1:-1]

array([[1, 2],
       [2, 1],
       [3, 2]])

In [6]:
ground_truth_positions[0:-2]

array([[0, 1],
       [1, 2],
       [2, 1]])

In [7]:
deltas

array([[ 1,  1],
       [ 1, -1],
       [ 1,  1]])

In [8]:
y = [el[1] for el in deltas]
print(y)

[1, -1, 1]


In [9]:
na = np.array(deltas)
print(na)

[[ 1  1]
 [ 1 -1]
 [ 1  1]]


In [10]:
print(na[:,1])

[ 1 -1  1]


In [11]:
ys = na[:,1]
print(ys)

[ 1 -1  1]


In [12]:
xs = na[:,0]
print(xs)

[1 1 1]


In [37]:
div = np.divide(ys, xs)
print(div)

[ 1. -1.  1.]


In [38]:
res = np.arctan(div)
print(res)

[ 0.78539816 -0.78539816  0.78539816]


In [72]:
result = 0
final = 0
for i in range(len(res)-1):
    for index in range(2):
        print("Adding ", res[index], "to result: ", result)
        result += res[index]
        print("Current result: ", result)
    final += np.absolute(result)


Adding  0.7853981633974483 to result:  0
Current result:  0.7853981633974483
Adding  -0.7853981633974483 to result:  0.7853981633974483
Current result:  0.0
Adding  0.7853981633974483 to result:  0.0
Current result:  0.7853981633974483
Adding  -0.7853981633974483 to result:  0.7853981633974483
Current result:  0.0


In [59]:
ground_truth_positions = [[0, 1], [1, 2], [2, 1], [3, 2]]

deltas = (ground_truth_positions[1:-1] - ground_truth_positions[0:-2])
sum_of_deltas = np.sum(deltas, axis=1)
curvature = sum_of_deltas.sum()

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [65]:
for i in range(2):
    print('ciao')

ciao
ciao
